#!/bin/sh
set -e

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR)

BACKEND_STAGED=$(echo "$STAGED_FILES" | grep -E "^packages/backend/" || true)
if [ -n "$BACKEND_STAGED" ]; then
  echo "Backend files changed, running lint --fix..."
  ./packages/backend/scripts/lint.ts --fix
  echo "$BACKEND_STAGED" | xargs git add
fi

FRONTEND_STAGED=$(echo "$STAGED_FILES" | grep -E "^packages/frontend/" || true)
if [ -n "$FRONTEND_STAGED" ]; then
  echo "Frontend files changed, running lint --fix..."
  ./packages/frontend/scripts/lint.ts --fix
  echo "$FRONTEND_STAGED" | xargs git add
fi
